# Generated by Django 2.2.2 on 2019-06-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190614_0455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
